version: "3"

tasks:
  chatbot:
    silent: true
    cmd: .venv/bin/python chatbot.py
  setup-kb:
    silent: true
    cmd: .venv/bin/python setup.py
  rustbot:
    silent: true
    cmd: .venv/bin/python rustbot.py

